// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKbPQz92JQrgNqnwa5xiwENc6P_UNIjQ',
    appId: '1:711725729724:web:e7b80edcaad28906cc0db9',
    messagingSenderId: '711725729724',
    projectId: 'phoenix-app-f2cdc',
    authDomain: 'phoenix-app-f2cdc.firebaseapp.com',
    storageBucket: 'phoenix-app-f2cdc.firebasestorage.app',
    measurementId: 'G-QDCHWDRJSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQKBAsshP64iVb-XjsRp6kUDCtkR83G0',
    appId: '1:711725729724:android:aa1a3f4cdf1f32d3cc0db9',
    messagingSenderId: '711725729724',
    projectId: 'phoenix-app-f2cdc',
    storageBucket: 'phoenix-app-f2cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3UiJAbA6I2Nut-ie8wh-fxqHoN8Ah60w',
    appId: '1:711725729724:ios:74fa90c80a665df8cc0db9',
    messagingSenderId: '711725729724',
    projectId: 'phoenix-app-f2cdc',
    storageBucket: 'phoenix-app-f2cdc.firebasestorage.app',
    iosBundleId: 'com.example.phoenixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3UiJAbA6I2Nut-ie8wh-fxqHoN8Ah60w',
    appId: '1:711725729724:ios:74fa90c80a665df8cc0db9',
    messagingSenderId: '711725729724',
    projectId: 'phoenix-app-f2cdc',
    storageBucket: 'phoenix-app-f2cdc.firebasestorage.app',
    iosBundleId: 'com.example.phoenixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAKbPQz92JQrgNqnwa5xiwENc6P_UNIjQ',
    appId: '1:711725729724:web:b0469e34d1bf28ebcc0db9',
    messagingSenderId: '711725729724',
    projectId: 'phoenix-app-f2cdc',
    authDomain: 'phoenix-app-f2cdc.firebaseapp.com',
    storageBucket: 'phoenix-app-f2cdc.firebasestorage.app',
    measurementId: 'G-435F29PC2Q',
  );
}
